# .pre-commit-config.yaml

exclude: 'docs|node_modules|migrations|terraform|.git|.tox'
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: removestar
        name: removestar
        stages: [pre-commit]
        language: system
        entry: removestar -i app
        types: [python]
      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: isort
        types: [python]
        args: [ "--profile", "black" ]
      - id: black
        name: black
        stages: [pre-commit]
        language: python
        entry: black app
        types: [python]
        language_version: python3.13
        args: [--target-version, py313, --line-length=120]
      - id: bandit
        name: bandit
        stages: [pre-commit]
        language: system
        entry: bandit -r app --ini=.bandit
        types: [python]
        pass_filenames: false
      - id: dodgy
        name: dodgy
        stages: [pre-commit]
        language: system
        entry: dodgy --ignore-paths=.venv
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: bash -c 'PYTHONPATH="$PYTHONPATH:$PWD" mypy'
        types: [python]
        pass_filenames: false
      - id: ruff
        name: ruff
        stages: [ pre-commit ]
        language: system
        entry: ruff check app
        types: [ python ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-ast
      - id: check-symlinks
      - id: forbid-new-submodules
