version: '3'

services:
  ragmate:
    image: ghcr.io/ragmate/ragmate:latest
    command: /bin/sh -c "gunicorn --workers 1 --max-requests 500 --bind 0.0.0.0:11434 -k uvicorn.workers.UvicornWorker app.main:app"
    ports:
      - "11434:11434"
    env_file:
      - ./.ragmate.env
    volumes:
      - .:/project
      - ./docker_data/ragmate:/apps/cache
